version: "1"
services:
        login-app:
            container_name: blogproject
            image: arshdeep/blogproject
            restart: always
            build: .
            ports:
              - "80:80"
            links:
              - mongo
        mongo:
              container_name: mongo
              image: mongo
              volumes:
                - ./data:/data/db
              ports:
                - '27018:27017'
